// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Adres

    {
        public int Id { get; set; }
        public int Bolumid { get; set; }
        public int Kartid { get; set; }
        public short Subtip { get; set; }
        public int Subid { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public int? Ulkeid { get; set; }
        public int? Sehirid { get; set; }
        public string Ilce { get; set; }
        public string Semt { get; set; }
        public string Postakodu { get; set; }
        public int? Bolgekoduid { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Fax { get; set; }
        public string Gsm { get; set; }
        public string Mail { get; set; }
        public string Url { get; set; }
        public string Notlar { get; set; }
        public bool? Varsayilan { get; set; }
        public string Kod { get; set; }
        public string Enlem { get; set; }
        public string Boylam { get; set; }
        public string Vergidairesi { get; set; }
        public string Vergino { get; set; }
        public short? Tel1info { get; set; }
        public string Binano { get; set; }
        public short? Smsiptal { get; set; }
    }
}