// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class CariFis
    {
        public int Id { get; set; }
        public int OwnBolumid { get; set; }
        public short OwnFistip { get; set; }
        public int? Ownerid { get; set; }
        public int Bolumid { get; set; }
        public short Fistip { get; set; }
        public string Fisno { get; set; }
        public DateTime Fistar { get; set; }
        public int Kartid { get; set; }
        public string Adi { get; set; }
        public decimal Tutar { get; set; }
        public int Dovizid { get; set; }
        public decimal? KurYerel { get; set; }
        public decimal YerelTutar { get; set; }
        public decimal? KurRapor { get; set; }
        public int CiKartid { get; set; }
        public string CiAdi { get; set; }
        public decimal CiTutar { get; set; }
        public int CiDovizid { get; set; }
        public decimal? CiKurYerel { get; set; }
        public decimal CiYerelTutar { get; set; }
        public int? Posaktarfisid { get; set; }
        public int? Muhfisid { get; set; }
        public bool Basimyapildi { get; set; }
        public decimal Kdvorani { get; set; }
        public decimal KdvMatrahi { get; set; }
        public decimal KdvTutari { get; set; }
        public DateTime? Kkislemtar { get; set; }
        public DateTime? Kkvade { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public short? HareketTipi { get; set; }
        public short? HareketAdedi { get; set; }
        public short? FaizTipi { get; set; }
        public short? YildaGun { get; set; }
        public decimal? VfYillikOrani { get; set; }
        public DateTime? OrtVade { get; set; }
        public short? OrtGun { get; set; }
        public decimal VfToplami { get; set; }
        public decimal VfTahsilEdilen { get; set; }
        public decimal VfTahsilEdilenYt { get; set; }
        public int? Subrecid { get; set; }
        public string Izah { get; set; }
        public string Notlar { get; set; }
        public int? Plasiyerid { get; set; }
        public int? Pcpostahsilid { get; set; }
        public decimal? Pcpostahsiltutar { get; set; }
        public int Subeid { get; set; }
        public int? CiSubeid { get; set; }
        public int? Yetkikodid { get; set; }
        public int? Genelgrup1 { get; set; }
        public int? Genelgrup2 { get; set; }
        public int? Genelgrup3 { get; set; }
        public int? Genelgrup4 { get; set; }
        public int? Genelgrup5 { get; set; }
        public string EvrakNo { get; set; }
        public decimal CiHesGecTutar { get; set; }
        public DateTime? Fissaat { get; set; }
        public int? HsKasaid { get; set; }
        public int? HsKasiyerid { get; set; }
        public decimal BkrdAnaPara { get; set; }
        public decimal BkrdFaizTutar { get; set; }
        public decimal BkrdBsmvTutar { get; set; }
        public decimal BkrdKkdfTutar { get; set; }
        public decimal BkrdErkenFaizTutar { get; set; }
        public decimal BkrdGecFaizTutar { get; set; }
    }
}