// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Cari
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public string Adi { get; set; }
        public bool Durum { get; set; }
        public short? Tip { get; set; }
        public int AlisOtPlanid { get; set; }
        public int SatisOtPlanid { get; set; }
        public decimal? Iskonto { get; set; }
        public int Aliskuryeriid { get; set; }
        public int Satiskuryeriid { get; set; }
        public int Dovizid { get; set; }
        public int AlisGrupid { get; set; }
        public int SatisGrupid { get; set; }
        public DateTime? MutabakatTarihi { get; set; }
        public bool Useirsadres { get; set; }
        public decimal AcikHesLimit { get; set; }
        public short? AcikHesLimitTipi { get; set; }
        public decimal CekSenetLimit { get; set; }
        public short? CekSenetLimitTipi { get; set; }
        public int? MuhhesAlis { get; set; }
        public int? MuhhesSatis { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public string Notlar { get; set; }
        public int? Plasiyerid { get; set; }
        public int? Yetkikodid { get; set; }
        public int? Iskmatrisid { get; set; }
        public short? Vadegunsayisi { get; set; }
        public int? ErpFasondepoid { get; set; }
        public bool? MustahsilBagkurKesintisi { get; set; }
        public string BagkurNumarasi { get; set; }
        public string SgkNumarasi { get; set; }
        public decimal? Iskonto2 { get; set; }
        public bool? Webdegoster { get; set; }
        public string B2bkullaniciadi { get; set; }
        public string B2bkullanicisifresi { get; set; }
        public int? Efatsenaryo { get; set; }
        public bool? Efatkullan { get; set; }
        public DateTime? Efattarih { get; set; }
        public string Efatalias { get; set; }
    }
}