// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class CariAylik
    {
        public int Kartid { get; set; }
        public int Dovizid { get; set; }
        public short Yil { get; set; }
        public short Ay { get; set; }
        public int Subeid { get; set; }
        public decimal DevirBorc { get; set; }
        public decimal DevirBorcYerel { get; set; }
        public decimal DevirBorcRapor { get; set; }
        public decimal DevirAlacak { get; set; }
        public decimal DevirAlacakYerel { get; set; }
        public decimal DevirAlacakRapor { get; set; }
        public decimal NakitBorc { get; set; }
        public decimal NakitBorcYerel { get; set; }
        public decimal NakitBorcRapor { get; set; }
        public decimal NakitAlacak { get; set; }
        public decimal NakitAlacakYerel { get; set; }
        public decimal NakitAlacakRapor { get; set; }
        public decimal CekBorc { get; set; }
        public decimal CekBorcYerel { get; set; }
        public decimal CekBorcRapor { get; set; }
        public decimal CekAlacak { get; set; }
        public decimal CekAlacakYerel { get; set; }
        public decimal CekAlacakRapor { get; set; }
        public decimal SenetBorc { get; set; }
        public decimal SenetBorcYerel { get; set; }
        public decimal SenetBorcRapor { get; set; }
        public decimal SenetAlacak { get; set; }
        public decimal SenetAlacakYerel { get; set; }
        public decimal SenetAlacakRapor { get; set; }
        public decimal FaturaBorc { get; set; }
        public decimal FaturaBorcYerel { get; set; }
        public decimal FaturaBorcRapor { get; set; }
        public decimal FaturaAlacak { get; set; }
        public decimal FaturaAlacakYerel { get; set; }
        public decimal FaturaAlacakRapor { get; set; }
        public decimal DekontBorc { get; set; }
        public decimal DekontBorcYerel { get; set; }
        public decimal DekontBorcRapor { get; set; }
        public decimal DekontAlacak { get; set; }
        public decimal DekontAlacakYerel { get; set; }
        public decimal DekontAlacakRapor { get; set; }
        public decimal BankaBorc { get; set; }
        public decimal BankaBorcYerel { get; set; }
        public decimal BankaBorcRapor { get; set; }
        public decimal BankaAlacak { get; set; }
        public decimal BankaAlacakYerel { get; set; }
        public decimal BankaAlacakRapor { get; set; }
        public decimal FirmakrediBorc { get; set; }
        public decimal FirmakrediBorcYerel { get; set; }
        public decimal FirmakrediBorcRapor { get; set; }
        public decimal? BorcTutar { get; set; }
        public decimal? BorcTutarYerel { get; set; }
        public decimal? BorcTutarRapor { get; set; }
        public decimal? AlacakTutar { get; set; }
        public decimal? AlacakTutarYerel { get; set; }
        public decimal? AlacakTutarRapor { get; set; }
    }
}