// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class CariHareket
    {
        public int Id { get; set; }
        public int OwnBolumid { get; set; }
        public int Ownerid { get; set; }
        public short? Fistipi { get; set; }
        public int Cariid { get; set; }
        public string Cariadi { get; set; }
        public string Evrakno { get; set; }
        public short Islemtipi { get; set; }
        public DateTime Islemtarihi { get; set; }
        public decimal Tutar { get; set; }
        public int Dovizid { get; set; }
        public decimal KurYerel { get; set; }
        public decimal YerelTutar { get; set; }
        public decimal KurRapor { get; set; }
        public string Izah { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public int Subeid { get; set; }
        public int? Yetkikodid { get; set; }
        public int? Genelgrup1 { get; set; }
        public int? Genelgrup2 { get; set; }
        public int? Genelgrup3 { get; set; }
        public int? Genelgrup4 { get; set; }
        public int? Genelgrup5 { get; set; }
        public DateTime? Islemsaati { get; set; }
    }
}