// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Dovizhareket
    {
        public int Id { get; set; }
        public DateTime? Gununtarihi { get; set; }
        public decimal? Dovİzfiyat { get; set; }
    }
}