// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpAltIsemri
    {
        public int Id { get; set; }
        public int Fisid { get; set; }
        public DateTime? Tarih { get; set; }
        public DateTime? Saat { get; set; }
        public string Isemrino { get; set; }
        public int UrunAgaciid { get; set; }
        public short? Sirano { get; set; }
        public int Stokid { get; set; }
        public decimal Miktar { get; set; }
        public decimal UretimMiktar { get; set; }
        public int Birimid { get; set; }
        public decimal Birim1katsayi { get; set; }
        public decimal Birim2katsayi { get; set; }
        public decimal Birim3katsayi { get; set; }
        public int Operasyonid { get; set; }
        public int Tezgahid { get; set; }
        public bool Demontaj { get; set; }
        public DateTime? BaslamaTarihi { get; set; }
        public DateTime? BaslamaSaati { get; set; }
        public decimal? GerekliSure { get; set; }
        public decimal? GerceklesenSure { get; set; }
        public DateTime? PlanBitisTarihi { get; set; }
        public DateTime? PlanBitisSaati { get; set; }
        public string Aciklama { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public int AnaUrunAgaciid { get; set; }
        public int Varyantid { get; set; }
        public short Statu { get; set; }
        public DateTime? PlanBaslamaTarihi { get; set; }
        public DateTime? PlanBaslamaSaati { get; set; }
        public DateTime? BitisTarihi { get; set; }
        public DateTime? BitisSaati { get; set; }
        public decimal? MhDeger1 { get; set; }
        public decimal? MhDeger2 { get; set; }
        public decimal? MhDeger3 { get; set; }
        public decimal? MhDeger4 { get; set; }
        public decimal? MhDeger5 { get; set; }
        public decimal? MhDeger6 { get; set; }
        public int? YarimamulSirano { get; set; }
        public string SiparisAciklama { get; set; }
        public int? ReferansNo { get; set; }
        public decimal? MhDeger8 { get; set; }
        public decimal? MhDeger7 { get; set; }
        public decimal? MhDeger9 { get; set; }
        public decimal? MhDeger10 { get; set; }
        public int? Batchid { get; set; }
    }
}