// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpIsemri
    {
        public int Id { get; set; }
        public string Fisno { get; set; }
        public DateTime? Fistar { get; set; }
        public DateTime? Fissaat { get; set; }
        public short? Statu { get; set; }
        public int? Stokid { get; set; }
        public bool? Demontaj { get; set; }
        public decimal? PaketMiktari { get; set; }
        public decimal? PaketIciMiktari { get; set; }
        public decimal? Miktar { get; set; }
        public int? Birimid { get; set; }
        public decimal Birim1katsayi { get; set; }
        public decimal Birim2katsayi { get; set; }
        public decimal Birim3katsayi { get; set; }
        public decimal? UretimMiktar { get; set; }
        public DateTime? TeslimTarihi { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public string Notlar { get; set; }
        public int? Varyantid { get; set; }
        public bool AltIsemriBirlestir { get; set; }
        public bool AlternatifKullan { get; set; }
        public decimal? MhDeger1 { get; set; }
        public decimal? MhDeger2 { get; set; }
        public decimal? MhDeger3 { get; set; }
        public decimal? MhDeger4 { get; set; }
        public decimal? MhDeger5 { get; set; }
        public decimal? MhDeger6 { get; set; }
        public int? ReferansNo { get; set; }
        public int? MrpNo { get; set; }
        public decimal? MhDeger7 { get; set; }
        public decimal? MhDeger8 { get; set; }
        public decimal? MhDeger9 { get; set; }
        public decimal? MhDeger10 { get; set; }
        public decimal? StokTutarThmn { get; set; }
        public decimal? IscilikTutarThmn { get; set; }
        public decimal? MakineTutarThmn { get; set; }
        public decimal? HurdaTutarThmn { get; set; }
        public decimal? FasonTutarThmn { get; set; }
        public decimal? GenelTutarThmn { get; set; }
        public decimal? StokTutarFiili { get; set; }
        public decimal? IscilikTutarFiili { get; set; }
        public decimal? MakineTutarFiili { get; set; }
        public decimal? HurdaTutarFiili { get; set; }
        public decimal? FasonTutarFiili { get; set; }
        public decimal? GenelTutarFiili { get; set; }
    }
}