// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpSevkEmriDetay
    {
        public int Id { get; set; }
        public int Fisid { get; set; }
        public int Sipharid { get; set; }
        public int Cariid { get; set; }
        public decimal SevkMiktar { get; set; }
        public decimal YuklenenMiktar { get; set; }
    }
}