// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpStokAmbalaj
    {
        public int Id { get; set; }
        public int Stokid { get; set; }
        public int Cariid { get; set; }
        public int Ambalajid { get; set; }
        public decimal Miktar { get; set; }
        public int Birimid { get; set; }
        public bool KarisikPaket { get; set; }
        public string AmbalajNo { get; set; }
    }
}