// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpStokOzellik
    {
        public int Id { get; set; }
        public int? Stokid { get; set; }
        public int? Ozellikid { get; set; }
        public int? OzellikDegerid { get; set; }
        public int? Sirano { get; set; }
    }
}