// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpSevkEmri
    {
        public int Id { get; set; }
        public string Fisno { get; set; }
        public DateTime Fistar { get; set; }
        public DateTime Fissaat { get; set; }
        public bool Yuklendi { get; set; }
        public string Aciklama { get; set; }
    }
}