// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpTezgah
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public string Adi { get; set; }
        public bool Tip { get; set; }
        public bool Durum { get; set; }
        public bool IcFason { get; set; }
        public int Cariid { get; set; }
        public short TezgahSayisi { get; set; }
        public decimal HedefDolulukOrani { get; set; }
        public int CalismaTakvimid { get; set; }
        public decimal NormalCalismaSure { get; set; }
        public decimal CumartesiCalismaSure { get; set; }
        public decimal PazarCalismaSure { get; set; }
        public int Depoid { get; set; }
        public int HammaddeDepoid { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public string Notlar { get; set; }
        public int Maliyetyeriid { get; set; }
        public int FireDepoid { get; set; }
    }
}