// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpTedarikci
    {
        public int Id { get; set; }
        public int Stokid { get; set; }
        public int Cariid { get; set; }
        public bool? Varsayilan { get; set; }
        public short? TedarikSuresi { get; set; }
        public decimal? MinimumSiparis { get; set; }
        public string TedStokKod { get; set; }
        public string TedStokAdi { get; set; }
        public string Aciklama { get; set; }
    }
}