// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpUrunAgaciDetay
    {
        public int Id { get; set; }
        public short? Sirano { get; set; }
        public int UrunAgaciid { get; set; }
        public short? AlternatifKod { get; set; }
        public short KaynakTuru { get; set; }
        public int Kaynakid { get; set; }
        public int Tezgahid { get; set; }
        public decimal? TezgahSure { get; set; }
        public decimal? AyarSure { get; set; }
        public short PartiSayisi { get; set; }
        public decimal? KaynakMiktari { get; set; }
        public int? Birimid { get; set; }
        public decimal Birim1katsayi { get; set; }
        public decimal Birim2katsayi { get; set; }
        public decimal Birim3katsayi { get; set; }
        public decimal SabitFireMiktar { get; set; }
        public bool SabitMiktarDurumu { get; set; }
        public string Aciklama { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public decimal? MhDeger1 { get; set; }
        public decimal? MhDeger2 { get; set; }
        public decimal? MhDeger3 { get; set; }
        public decimal? MhDeger4 { get; set; }
        public decimal? MhDeger5 { get; set; }
        public decimal? MhDeger6 { get; set; }
        public string VaryantKosulu { get; set; }
        public string VaryantTanimi { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string AmbalajNo { get; set; }
        public string MhDegerFormul1 { get; set; }
        public string MhDegerFormul2 { get; set; }
        public string MhDegerFormul3 { get; set; }
        public string MhDegerFormul4 { get; set; }
        public string MhDegerFormul5 { get; set; }
        public string MhDegerFormul6 { get; set; }
        public int? SarfOperasyonid { get; set; }
        public decimal? MhDeger7 { get; set; }
        public string MhDegerFormul7 { get; set; }
        public decimal? MhDeger8 { get; set; }
        public decimal? MhDeger9 { get; set; }
        public decimal? MhDeger10 { get; set; }
        public string MhDegerFormul8 { get; set; }
        public string MhDegerFormul9 { get; set; }
        public string MhDegerFormul10 { get; set; }
    }
}