// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpUrunAgaci
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public string Adi { get; set; }
        public bool Durum { get; set; }
        public int Stokid { get; set; }
        public decimal Miktar { get; set; }
        public int Birimid { get; set; }
        public bool Demontaj { get; set; }
        public string Aciklama { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public int? Ozelgrup6 { get; set; }
        public int? Ozelgrup7 { get; set; }
        public int? Ozelgrup8 { get; set; }
        public int? Ozelgrup9 { get; set; }
        public int? Ozelgrup10 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public string Ozelalan6 { get; set; }
        public string Ozelalan7 { get; set; }
        public string Ozelalan8 { get; set; }
        public string Ozelalan9 { get; set; }
        public string Ozelalan10 { get; set; }
        public decimal Birim1katsayi { get; set; }
        public decimal Birim2katsayi { get; set; }
        public decimal Birim3katsayi { get; set; }
        public DateTime? Tarih { get; set; }
        public DateTime? Saat { get; set; }
        public int UrunAnahtari { get; set; }
    }
}