// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpUretimPanelOperasyon
    {
        public int Id { get; set; }
        public int? BatchId { get; set; }
        public int? SonOperasyonId { get; set; }
    }
}