// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpUretimFisi
    {
        public int Id { get; set; }
        public string Fisno { get; set; }
        public short? Fistip { get; set; }
        public int? Cariid { get; set; }
        public DateTime? Fistar { get; set; }
        public DateTime? Fissaat { get; set; }
        public int? HammaddeDepoid { get; set; }
        public int? ImalatDepoid { get; set; }
        public int? YanurunDepoid { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public int? Subeid { get; set; }
    }
}