// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpUretimPanel
    {
        public int Id { get; set; }
        public int? OwnerId { get; set; }
        public int? OperatorId { get; set; }
        public string OperatorKod { get; set; }
        public int? IsemriId { get; set; }
        public string IsemriNo { get; set; }
        public int? AltisemriId { get; set; }
        public string AltisemriNo { get; set; }
        public int? TezgahId { get; set; }
        public string TezgahKod { get; set; }
        public int? OperasyonId { get; set; }
        public string OperasyonKod { get; set; }
        public DateTime? BaslamaTarihi { get; set; }
        public DateTime? BaslamaSaati { get; set; }
        public string PanelKod { get; set; }
        public int? DurusId { get; set; }
        public DateTime? DurusBaslamaTarihi { get; set; }
        public DateTime? DurusBaslamaSaati { get; set; }
        public DateTime? DurusBitisTarihi { get; set; }
        public DateTime? DurusBitisSaati { get; set; }
        public bool? Tamamlandi { get; set; }
        public DateTime? BitisTarihi { get; set; }
        public DateTime? BitisSaati { get; set; }
    }
}