// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpUretimFisiDetay
    {
        public int Id { get; set; }
        public int? Fisid { get; set; }
        public int? Isemriid { get; set; }
        public int? Altisemriid { get; set; }
        public int? Stokid { get; set; }
        public decimal? Miktar { get; set; }
        public int? Birimid { get; set; }
        public decimal Birim1katsayi { get; set; }
        public decimal Birim2katsayi { get; set; }
        public decimal Birim3katsayi { get; set; }
        public int? Lotid { get; set; }
        public int? Seriid { get; set; }
        public int? Depoid { get; set; }
        public decimal MhDeger1 { get; set; }
        public decimal MhDeger2 { get; set; }
        public decimal MhDeger3 { get; set; }
        public decimal MhDeger4 { get; set; }
        public decimal MhDeger5 { get; set; }
        public decimal MhDeger6 { get; set; }
        public int? ErpVaryantid { get; set; }
        public string UretimeKatilacak { get; set; }
        public decimal? FireMiktar { get; set; }
        public int? Fireid { get; set; }
    }
}