// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpUretimPanelDurum
    {
        public int Id { get; set; }
        public int? Tezgahid { get; set; }
        public int? Durusid { get; set; }
        public int? Durum { get; set; }
    }
}