// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class ErpVaryantOlcu
    {
        public int Id { get; set; }
        public int Stokid { get; set; }
        public string VaryantKosulu { get; set; }
        public decimal? NetagirlikKg { get; set; }
        public decimal? DaraKg { get; set; }
        public decimal? EnMm { get; set; }
        public decimal? BoyMm { get; set; }
        public decimal? YukseklikMm { get; set; }
        public decimal? Depozito { get; set; }
        public decimal? AlanM2 { get; set; }
        public decimal? Bruthacim { get; set; }
        public decimal? Nethacim { get; set; }
    }
}