// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Fiyat
    {
        public int Id { get; set; }
        public float? Boyanetutar { get; set; }
        public float? Paketlemetutar { get; set; }
        public float? Hammalzeme { get; set; }
        public float? Tamburmaliyet { get; set; }
        public float? Beilirtilmemisgider1 { get; set; }
        public float? Beilirtilmemisgider2 { get; set; }
        public float? Fasonfiyat { get; set; }
        public float? Iplikbedeli { get; set; }
        public float? Zeminbedeli { get; set; }
        public float? Kesimbedeli { get; set; }
        public float? Boyabedeli { get; set; }
        public float? Toplammammaliyet { get; set; }
        public float? Fire { get; set; }
        public float? Kar { get; set; }
        public float? Geneltoplammetremaliyet { get; set; }
        public float? Dovizkuru { get; set; }
        public float? Parekendesatisfiyati { get; set; }
    }
}