// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Grup
    {
        public int Id { get; set; }
        public int Ownerid { get; set; }
        public short Tip { get; set; }
        public string Kod { get; set; }
        public string Izah { get; set; }
        public string Izah2 { get; set; }
        public int? EfatGrupid { get; set; }
    }
}