// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class HizliSatisTanim
    {
        public int Id { get; set; }
        public short Sirano { get; set; }
        public int Grupid { get; set; }
        public int Stokid { get; set; }
        public int? Renk { get; set; }
        public string GorunenAdi { get; set; }
        public int Subeid { get; set; }
        public string Stoktip { get; set; }
        public int? Birimid { get; set; }
        public decimal? Dara { get; set; }
    }
}