// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class KurBaglanti1
    {
        public int Id { get; set; }
        public short Astip { get; set; }
        public DateTime? Tarih { get; set; }
        public DateTime? Saat { get; set; }
        public string Bankakodu { get; set; }
        public string Dovizkodu { get; set; }
        public string Dovizadi { get; set; }
        public decimal Tutar { get; set; }
    }
}