// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class KurBaglanti2
    {
        public int Id { get; set; }
        public int Dovizid { get; set; }
        public int Kuryeriid { get; set; }
        public int Kurbag1id { get; set; }
    }
}