// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Kurgiris
    {
        public int Id { get; set; }
        public DateTime Tarih { get; set; }
        public int Dovizid { get; set; }
        public int Kuryeriid { get; set; }
        public decimal Kurvalue { get; set; }
    }
}