// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Loginfo
    {
        public string Logkey { get; set; }
        public DateTime? Logzaman { get; set; }
        public string Aktivite { get; set; }
        public DateTime? Zaman { get; set; }
        public short? Yerid { get; set; }
        public int? Bolumid { get; set; }
        public int? Kayitid { get; set; }
        public string Islem { get; set; }
        public string Kullanici { get; set; }
        public string XmlData { get; set; }
    }
}