// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Paket
    {
        public int Id { get; set; }
        public DateTime? Tarih { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public string Ozelalan6 { get; set; }
        public float? Kilo { get; set; }
        public int? Adet { get; set; }
        public bool? Sonuclardirma { get; set; }
        public string Barkod { get; set; }
        public bool? Isemri { get; set; }
        public bool? Yazdirildi { get; set; }
    }
}