// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Paketdeger
    {
        public int Id { get; set; }
        public DateTime? Tarih { get; set; }
        public float? Metre { get; set; }
        public float? Tezgahboy { get; set; }
        public float? Paketkg { get; set; }
        public float? Girisbirim1 { get; set; }
        public int? Girisadet { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public int? Paketno { get; set; }
        public int? Partino { get; set; }
        public float? Girisbirim2 { get; set; }
    }
}