// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Paketonay
    {
        public int Id { get; set; }
        public DateTime? Tarih { get; set; }
        public int? Urunadet { get; set; }
        public float? Kg { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Paketno { get; set; }
        public bool? Tamalandi { get; set; }
        public int? Girisbirimkatkod { get; set; }
    }
}