// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Personel
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public int Isyeriid { get; set; }
        public int Cariid { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Ilksoyadi { get; set; }
        public string Vergidaire { get; set; }
        public string Vergino { get; set; }
        public string Sigortano { get; set; }
        public string Kontrolno { get; set; }
        public short? Sgk { get; set; }
        public string Sgkdiger { get; set; }
        public string Sgksicilno { get; set; }
        public bool Sgkaylik { get; set; }
        public short? Sgstatusu { get; set; }
        public short? GorevKodu { get; set; }
        public bool GelirvergisiMuaf { get; set; }
        public bool DamgavergisiMuaf { get; set; }
        public bool Issizlik { get; set; }
        public short? Sakatderece { get; set; }
        public short? Istihdam1 { get; set; }
        public short? Istihdam2 { get; set; }
        public string Istihdamdiger { get; set; }
        public bool Hukumlu { get; set; }
        public bool Terormaduru { get; set; }
        public int? Gorevid { get; set; }
        public int? Departmanid { get; set; }
        public short? Ogrenim { get; set; }
        public string Ogrenimdiger { get; set; }
        public bool Uyruktc { get; set; }
        public int? Uyrukid { get; set; }
        public DateTime? Giristarih { get; set; }
        public DateTime? Cikistarih { get; set; }
        public int? Cikissebepid { get; set; }
        public DateTime? Ilkgiristarih { get; set; }
        public bool KidihbGiristarih { get; set; }
        public short? Ucretturu { get; set; }
        public bool Ucrettipi { get; set; }
        public bool Ayliknet { get; set; }
        public decimal? Ucret { get; set; }
        public int? Parabirimi { get; set; }
        public int? Kuryeri { get; set; }
        public decimal? Avanslimiti { get; set; }
        public string Onceisyerunvan { get; set; }
        public decimal? Onceisyerkmat { get; set; }
        public int? Sigortakoduid { get; set; }
        public int? Kanunnoid { get; set; }
        public string Ehliyet { get; set; }
        public string Notlar { get; set; }
        public bool Asgarigecim { get; set; }
        public bool Kontenjanfazlasiozurlu { get; set; }
        public short? Sigortalilikturu { get; set; }
        public short? Sigortalilikkodu { get; set; }
        public int? Yetkikodid { get; set; }
        public string PdksKod { get; set; }
        public int? PdksVardiyaid { get; set; }
        public bool? PdksVardiyasiz { get; set; }
        public short PdksFazlamesai { get; set; }
        public bool Iscikiskart { get; set; }
        public short? PdksTatilgun { get; set; }
        public short? PdksEksiksaat { get; set; }
        public short? PdksIzintolerans { get; set; }
        public bool PdksOzelcalisma { get; set; }
        public decimal? PdksGunlukcalismasaat { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public DateTime? Gecerlilik6111 { get; set; }
        public int? ErpOperatorTurid { get; set; }
        /// <summary>
        /// SGK Aylık Bildirgesine Meslek Kodu alanının eklenmesi sonucu oluşturuldu.
        /// </summary>
        public int Meslekid { get; set; }
        public DateTime? IzinDevirTarih { get; set; }
        public int OncekiCalisGunSay { get; set; }
        public int IzinDevirGunSay { get; set; }
        public short? PdksErkenGirisSaat { get; set; }
        public int AgiHesapIsyeriid { get; set; }
        public short? PdksGecCikisSaat { get; set; }
        public DateTime? VardiyasizBasSaat { get; set; }
        public int Bankaid { get; set; }
        public bool? AsgariTesvikIndirimi { get; set; }
        public bool CumartesiTatil { get; set; }
        public bool BesKesintisi { get; set; }
        public decimal BesKesintiOrani { get; set; }
        public decimal BesKesintiTutari { get; set; }
        public bool IstihdamTesvik { get; set; }
        public bool PdksFazlaMesDenkleNormal { get; set; }
        public bool PdksFazlaMesDenkleCumartesi { get; set; }
        public bool PdksFazlaMesDenkleHaftasonu { get; set; }
        public bool PdksFazlaMesDenkleEksikgun { get; set; }
        public string OgrenimBolumAdi { get; set; }
        public short? OgrenimMezunYili { get; set; }
    }
}