// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class SatinalmaSozlesmeFis
    {
        public int Id { get; set; }
        public int Bolumid { get; set; }
        public short? Fistip { get; set; }
        public string Fisno { get; set; }
        public string Adi { get; set; }
        public DateTime Fistarih { get; set; }
        public DateTime Fissaat { get; set; }
        public DateTime? SozBasTarih { get; set; }
        public DateTime? SozBitTarih { get; set; }
        public string Aciklama { get; set; }
        public int Cariid { get; set; }
        public string Cariadi { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Notlar { get; set; }
        public int Subeid { get; set; }
        public int? Yetkikodid { get; set; }
        public int? Genelgrup1 { get; set; }
        public int? Genelgrup2 { get; set; }
        public int? Genelgrup3 { get; set; }
        public int? Genelgrup4 { get; set; }
        public int? Genelgrup5 { get; set; }
        public decimal? PIskonto1 { get; set; }
        public decimal? PIskonto2 { get; set; }
        public decimal? PIskonto3 { get; set; }
        public decimal? PIskonto4 { get; set; }
        public decimal? PIskonto5 { get; set; }
        public decimal? PgIskonto1 { get; set; }
        public decimal? PgIskonto2 { get; set; }
        public decimal? VIskonto1 { get; set; }
        public decimal? VIskonto2 { get; set; }
        public decimal? VIskonto3 { get; set; }
        public decimal? VIskonto4 { get; set; }
        public decimal? VIskonto5 { get; set; }
        public decimal? VgIskonto1 { get; set; }
        public decimal? VgIskonto2 { get; set; }
        public int? POtplanid { get; set; }
        public int? VOtplanid { get; set; }
        public short? PGun { get; set; }
        public short? VGun { get; set; }
    }
}