// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Satis
    {
        public int Id { get; set; }
        public decimal? Toplamtl { get; set; }
        public decimal? Toplamdolar { get; set; }
        public decimal? Birimdolar { get; set; }
        public decimal? Iskonto { get; set; }
        public decimal? Tahsilat { get; set; }
        public int? Cariid { get; set; }
        public DateTime? Tarih { get; set; }
        public decimal? Toplammt { get; set; }
        public string Odemeturu { get; set; }
    }
}