// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class SatinalmaSozCiroDetay
    {
        public int Id { get; set; }
        public int? Fisid { get; set; }
        public int? Ciroid { get; set; }
        public short? Ay { get; set; }
        public short? Donem { get; set; }
        public decimal? TutarAlis { get; set; }
        public decimal? TutarAlisIade { get; set; }
        public decimal? TutarFiyatFarki { get; set; }
        public decimal? TutarPrim1 { get; set; }
        public decimal? TutarPrim2 { get; set; }
        public decimal? TutarPrim3 { get; set; }
        public int? Faturaid1 { get; set; }
        public int? Faturaid2 { get; set; }
        public int? Faturaid3 { get; set; }
    }
}