// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class SatinalmaSozCiro
    {
        public int Id { get; set; }
        public int? Fisid { get; set; }
        public decimal? Hedeflenen { get; set; }
        public short? PrimHesaplamaTipi { get; set; }
        public short? Periyot { get; set; }
        public short? PrimDonemi { get; set; }
        public short? Aylar { get; set; }
        public decimal? Oran1 { get; set; }
        public decimal? Oran2 { get; set; }
        public decimal? Oran3 { get; set; }
        public bool? FiyatFarki { get; set; }
        public bool? IadeFaturalar { get; set; }
        public int? Hizmetid { get; set; }
        public int? StokGrupid { get; set; }
    }
}