// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Sevkiyat
    {
        public int Id { get; set; }
        public string Aciklama { get; set; }
        public string Cari { get; set; }
        public string Zemin { get; set; }
        public decimal? Toplamfiyat { get; set; }
        public decimal? Toplammetre { get; set; }
        public DateTime? Islemtarihi { get; set; }
        public string En { get; set; }
    }
}