// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Sevkiyattamamlama
    {
        public int Id { get; set; }
        public int? Musteriid { get; set; }
        public float? Toplammetre { get; set; }
        public float? Toplamtutar { get; set; }
        public DateTime? Tarih { get; set; }
    }
}