// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Sevkiyatdetay
    {
        public int Id { get; set; }
        public int? Sira { get; set; }
        public int? Sevkiyatkodu { get; set; }
        public int? Stokkodu { get; set; }
        public double? Metre { get; set; }
        public decimal? Fiyat { get; set; }
    }
}