// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Siparis
    {
        public int Id { get; set; }
        public int? Firmaid { get; set; }
        public DateTime? Siptarihi { get; set; }
        public int? Rptid { get; set; }
        public int? Desenid { get; set; }
        public int? Zemİnid { get; set; }
        public int? Ipid { get; set; }
        public int? Renkid { get; set; }
        public DateTime? Makurttar { get; set; }
        public int? Kuponad { get; set; }
        public string Urdurum { get; set; }
        public int? Musteriid { get; set; }
        public DateTime? Teslimtarihi { get; set; }
        public int? Uretilenkupon { get; set; }
        public int? Ipid2 { get; set; }
        public float? Metre { get; set; }
        public decimal? Fiyat { get; set; }
        public decimal? Tutar { get; set; }
        public bool? DurumBekleyen { get; set; }
        public bool? DurumIslemealinan { get; set; }
        public bool? DurumTamamlanan { get; set; }
        public int? Makinaid { get; set; }
        public int? Kortipid { get; set; }
        public int? Kupondagimiid { get; set; }
        public int? Ozelkod { get; set; }

        public virtual UrtCizim Desen { get; set; }
    }
}