// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class TeklifHar
    {
        public int Id { get; set; }
        public short Sirano { get; set; }
        public short Fistip { get; set; }
        public int Fisid { get; set; }
        public DateTime Fistar { get; set; }
        public string Karttipi { get; set; }
        public int Kartid { get; set; }
        public int Barkodid { get; set; }
        public decimal Miktar { get; set; }
        public int Birimid { get; set; }
        public decimal Birim1katsayi { get; set; }
        public decimal Birim2katsayi { get; set; }
        public decimal Birim3katsayi { get; set; }
        public decimal Fiyat { get; set; }
        public decimal Dfiyat { get; set; }
        public int Dovizid { get; set; }
        public decimal KurYerel { get; set; }
        public decimal KurRapor { get; set; }
        public decimal Tutar { get; set; }
        public decimal Dtutar { get; set; }
        public decimal Kdvorani { get; set; }
        public decimal Kdvmatrahi { get; set; }
        public decimal Kdvtutari { get; set; }
        public decimal? Iskonto1 { get; set; }
        public decimal? Iskonto2 { get; set; }
        public decimal? Iskonto3 { get; set; }
        public decimal? Iskonto4 { get; set; }
        public decimal? Iskonto5 { get; set; }
        public decimal Iskonto1tutar { get; set; }
        public decimal Iskonto2tutar { get; set; }
        public decimal Iskonto3tutar { get; set; }
        public decimal Iskonto4tutar { get; set; }
        public decimal Iskonto5tutar { get; set; }
        public decimal Fisisk1tutar { get; set; }
        public decimal Fisisk2tutar { get; set; }
        public int Otplanid { get; set; }
        public DateTime? VadeTarihi { get; set; }
        public int Depoid { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Aciklama { get; set; }
        public int? OwnerStokId { get; set; }
        public int? OwnerTreeId { get; set; }
        public int? Otvid { get; set; }
        public int? Otvharid { get; set; }
        public decimal Otvmatrahi { get; set; }
        public decimal Otvtutari { get; set; }
        public decimal Otvindirimi { get; set; }
        public int? Talimatid { get; set; }
        public int? Faturaid { get; set; }
        public int? Irsaliyeid { get; set; }
        public int? Siparisid { get; set; }
        public int Subeid { get; set; }
        public int? Yetkikodid { get; set; }
        public int? Genelgrup1 { get; set; }
        public int? Genelgrup2 { get; set; }
        public int? Genelgrup3 { get; set; }
        public int? Genelgrup4 { get; set; }
        public int? Genelgrup5 { get; set; }
        public int? Bolumid { get; set; }
        public int? Ownerid { get; set; }
        public int? Departmanid { get; set; }
        public int? ErpVaryantid { get; set; }
        public decimal? MhDeger1 { get; set; }
        public decimal? MhDeger2 { get; set; }
        public decimal? MhDeger3 { get; set; }
        public decimal? MhDeger4 { get; set; }
        public decimal? MhDeger5 { get; set; }
        public decimal? MhDeger6 { get; set; }
        public decimal? MhDeger7 { get; set; }
        public decimal? MhDeger8 { get; set; }
        public decimal? MhDeger9 { get; set; }
        public decimal? MhDeger10 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
    }
}