// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class TeklifYetki
    {
        public int Id { get; set; }
        public int Userid { get; set; }
        public bool SatOnay { get; set; }
        public bool SatRet { get; set; }
        public bool AlisOnay { get; set; }
        public bool AlisRet { get; set; }
        public bool SatisOnay { get; set; }
        public bool SatisRet { get; set; }
    }
}