// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Teklif
    {
        public int Id { get; set; }
        public short Tip { get; set; }
        public string Fisno { get; set; }
        public DateTime Fistar { get; set; }
        public DateTime? Fissaat { get; set; }
        public bool Kdvdahil { get; set; }
        public bool Kdvdahilisk { get; set; }
        public int Cariid { get; set; }
        public string Cariadi { get; set; }
        public short? Odurumu { get; set; }
        public string Talimatno { get; set; }
        public int? Musteriid { get; set; }
        public short Dovizusetip { get; set; }
        public DateTime? Vadesi { get; set; }
        public int Otplanid { get; set; }
        public int Depoid { get; set; }
        public decimal Stoktoplam { get; set; }
        public decimal Hizmettoplam { get; set; }
        public decimal Kalemisktoplam { get; set; }
        public decimal Kalemkdvtoplam { get; set; }
        public decimal Iskoran1 { get; set; }
        public decimal Isktutar1 { get; set; }
        public decimal Iskoran2 { get; set; }
        public decimal Isktutar2 { get; set; }
        public decimal Aratoplam { get; set; }
        public decimal Fiskdvtutari { get; set; }
        public decimal Geneltoplam { get; set; }
        public decimal KurRapor { get; set; }
        public decimal GeneltoplamRapor { get; set; }
        public decimal KurValue { get; set; }
        public decimal GeneltoplamCari { get; set; }
        public int Dovizid { get; set; }
        public decimal Otvtoplami { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Postakodu { get; set; }
        public string Vergino { get; set; }
        public string Vergidairesi { get; set; }
        public bool Basildi { get; set; }
        public short? Dovizliharcount { get; set; }
        public int? Ozelgrup1 { get; set; }
        public int? Ozelgrup2 { get; set; }
        public int? Ozelgrup3 { get; set; }
        public int? Ozelgrup4 { get; set; }
        public int? Ozelgrup5 { get; set; }
        public string Ozelalan1 { get; set; }
        public string Ozelalan2 { get; set; }
        public string Ozelalan3 { get; set; }
        public string Ozelalan4 { get; set; }
        public string Ozelalan5 { get; set; }
        public bool Onodemeliteklif { get; set; }
        public int Irsaliyeid { get; set; }
        public int Faturaid { get; set; }
        public int Siparisid { get; set; }
        public int Talimatid { get; set; }
        public string Notlar { get; set; }
        public int Subeid { get; set; }
        public int? Yetkikodid { get; set; }
        public int? Genelgrup1 { get; set; }
        public int? Genelgrup2 { get; set; }
        public int? Genelgrup3 { get; set; }
        public int? Genelgrup4 { get; set; }
        public int? Genelgrup5 { get; set; }
        public int? Userid { get; set; }
        public int? Bolumid { get; set; }
        public int? Ownerid { get; set; }
        public int? Departmanid { get; set; }
        public decimal? MhDeger1 { get; set; }
        public decimal? MhDeger2 { get; set; }
        public decimal? MhDeger3 { get; set; }
        public decimal? MhDeger4 { get; set; }
        public decimal? MhDeger5 { get; set; }
        public decimal? MhDeger6 { get; set; }
    }
}