// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UretimTekstilParca
    {
        public int Barkodid { get; set; }
        public int? Uretimid { get; set; }
        public string Ip { get; set; }
        public string Desenno { get; set; }
        public string Firma { get; set; }
        public decimal? Desenvurus { get; set; }
        public string Renk { get; set; }
        public string Makineno { get; set; }
        public int? Kuponno { get; set; }
        public string Boyane { get; set; }
        public DateTime? Uretimtar { get; set; }
        public DateTime? Bgszmn { get; set; }
        public string Barcode { get; set; }
        public string Kumas2 { get; set; }
        public string Raport { get; set; }
        public string Kumas { get; set; }
        public string Uretimdurum { get; set; }
        public string Kalite { get; set; }
        public string Kort { get; set; }
        public float? Metre { get; set; }
        public string Renkkodu { get; set; }
        public bool? Boyanehazir { get; set; }
        public int? Musteriid { get; set; }
        public bool? Satisdepo { get; set; }
        public bool? Gonderildi { get; set; }
        public float? Tuketilen { get; set; }
        public bool? Stokdusum { get; set; }
        public float? Metreham { get; set; }
        public bool? Basildimi { get; set; }
    }
}