// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UrtCizimSure
    {
        public int Id { get; set; }
        public int? Desenid { get; set; }
        public decimal? Desensurezaman { get; set; }
    }
}