// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UrtKategoriAltGrup
    {
        public int Id { get; set; }
        public string Mamulzeminkumas { get; set; }
        public string Kod { get; set; }
    }
}