// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UrtKategoriUstGrup
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public bool? Degerlendirme { get; set; }
        public bool? Hazirmal { get; set; }
    }
}