// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UrtMakine
    {
        public int Id { get; set; }
        public string Makineno { get; set; }
        public string Model { get; set; }
        public string Ozelalan1 { get; set; }
        public int? Ozelgrup1 { get; set; }
        public float? Ozeldeger1 { get; set; }
        public decimal? Ozeldeger2 { get; set; }
    }
}