// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UrtMakineDeger
    {
        public int Id { get; set; }
        public DateTime? Tarih { get; set; }
        public decimal? Vurus { get; set; }
        public int? Kuponadet { get; set; }
        public float? Performansorani { get; set; }
        public decimal? Ongorulensaatvurus { get; set; }
    }
}