// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UrtSevkBirim
    {
        public int Id { get; set; }
        public decimal? Partino { get; set; }
        public int? Topadet { get; set; }
        public float? Topmetre { get; set; }
        public DateTime? Tarih { get; set; }
        public DateTime? Teslimtarihi { get; set; }
        public int? Gelenbirimadet { get; set; }
        public float? Kg { get; set; }
    }
}