// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class UrtVardiya
    {
        public int Id { get; set; }
        public string Vardiyadonem { get; set; }
        public string Personel { get; set; }
        public string VurusKartmetre { get; set; }
        public string Vardiyaraligi { get; set; }
        public DateTime? Calismazamani { get; set; }
        public string Desen1 { get; set; }
        public string Desen2 { get; set; }
        public string Desen3 { get; set; }
        public string Vardiyaamiri { get; set; }
        public string Kumasdegisimi { get; set; }
        public string Barkotno { get; set; }
        public string Mekikturu { get; set; }
        public string Saat { get; set; }
        public string Ariza { get; set; }
        public int? Toplamkupon { get; set; }
        public string Makinano { get; set; }
        public string Mekiksaat { get; set; }
        public int? Zemindegisim { get; set; }
        public decimal? Vardiyavurus { get; set; }
        public float? Vardiyafiyat { get; set; }
        public byte[] Vardiya { get; set; }
    }
}