// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Users
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Namesurname { get; set; }
        public string Pasword { get; set; }
        public string Access { get; set; }
        public string Parametre { get; set; }
        public byte[] NavbarIcon { get; set; }
        public byte[] Wallpaper { get; set; }
        public string Shortmenu { get; set; }
        public bool? HizliSatisYetki { get; set; }
        public string Rol { get; set; }
        public bool? Sistemdurumu { get; set; }
        public string Port { get; set; }
    }
}