// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Yetkili
    {
        public int Id { get; set; }
        public int Bolumid { get; set; }
        public int Kartid { get; set; }
        public string Adi { get; set; }
        public string Unvan { get; set; }
        public string Notlar { get; set; }
    }
}