// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MrpAndSalesFactory.Entity.Models
{
    public partial class Yetki
    {
        public int? Userid { get; set; }
        public int? Bolumid { get; set; }
        public int? Gorme { get; set; }
        public int? Yeni { get; set; }
        public int? Sil { get; set; }
        public int? Degistir { get; set; }
        public int? Yazdir { get; set; }
        public int? Sifresor { get; set; }
        public string Sifre { get; set; }
    }
}